accounts/urls.py
from django.conf.urls import url
from accounts.views import LoginView, LogoutView, SignupView

app_name = 'accounts'

urlpatterns = [
    url("^signup/$", SignupView.as_view(), name='signup'),
    url("^login/$", LoginView.as_view(), name="login"),
    url("^logout/$", LogoutView.as_view(), name="logout"),
]

foodie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from posts.views import PostList, PostCreate, PostLikeToggle, PostDetail
from telebot_api.views import BotView
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', PostList.as_view(), name='list'),
    path('bot/webhook', csrf_exempt(BotView.as_view())),
]

handler404 = 'posts.views.custom_404_error'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from django.urls import path, include
from posts.views import PostCreate, PostLikeToggle, PostDetail, PostList, PostEdit

app_name = 'posts'

urlpatterns = [
    path("", PostList.as_view(), name="list"),
    path('new/', PostCreate.as_view(), name='new'),
    path('<pk>/edit/', PostEdit.as_view(), name='edit'),
    path("<pk>/like/", PostLikeToggle.as_view(), name='like'),
    path("<pk>/", PostDetail.as_view(), name='detail')
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User, UserManager
from django.urls import reverse
from django.template.defaultfilters import slugify
import random
import string


def randomString():
    um = UserManager()
    return( um.make_random_password(length=25))

class Post(models.Model):
    image = models.ImageField()
    description = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=300)
    likes = models.ManyToManyField('Like', related_name='post_likes')

    class Meta: 
       ordering = ('-created', '-modified', ) 

    def save(self, *args, **kwargs):
        slug = slugify(self.description + '-' + self.created.date().strftime('%Y-%m-%d'))
        # slug = ''.join(random.sample(string.ascii_lowercase, 10))
        self.slug = slug
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self, pk):
        return reverse("posts:detail", kwargs={"pk": pk})
    

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    is_liked = models.BooleanField(default=False)
    date = models.DateField(auto_now=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View
from django.contrib.auth import login, logout

class SignupView(View):
    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #  log the user in
            login(request, user)
            return redirect(reverse('posts:list'))
        return render(request, 'accounts/signup.html', { 'form': form })

    def get(self, request):
        form = UserCreationForm()
        return render(request, 'accounts/signup.html', { 'form': form })


class LoginView(View):
    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect(reverse('posts:list'))
        return render(request, 'accounts/login.html', { 'form': form })

    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', { 'form': form })

class LogoutView(View):
    def post(self, request):
        logout(request)
        return redirect(reverse('posts:list'))

posts/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import RedirectView
from django.shortcuts import get_object_or_404
from django.db import transaction
# Create your views here.
from posts.models import Post, Like

class PostList(ListView):
    model = Post

class PostLikeToggle(RedirectView):
    @transaction.atomic
    def get_redirect_url(self, *args, **kwargs):
        post_id = kwargs.get('pk')
        post = get_object_or_404(Post, id=post_id)
        user = self.request.user
        like = Like.objects.get_or_create(user=user, post=post)[0]
        print("Like", like.is_liked)
        if like.is_liked:
            like.is_liked = False
            post.likes.remove(like)
        else:
            like.is_liked = True
            post.likes.add(like)
        like.save()
        url_redirect = post.get_absolute_url(post_id)
        return url_redirect

class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['image', 'description']
    template_name = 'posts/post_new.html'
    success_url = '/'
    login_url = '/accounts/login'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostEdit(UpdateView):
    model = Post
    fields = ['image', 'description']
    template_name = 'posts/post_edit.html'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context
        
def custom_404_error(request, exception):
    print(request.path)
    data = {
        'method': request.method,
        'uri': request.path
        }
    return render(request,  'post_404.html', data)

telebot_api/views.py
from django.shortcuts import render

import requests
import json
import telebot

from django.http import JsonResponse
from django.views import View
from django.conf import settings

from posts.models import Post

TELEGRAM_URL = settings.TELEGRAM_URL
BOT_TOKEN = settings.BOT_TOKEN

tb = telebot.TeleBot(BOT_TOKEN, threaded=False)

class BotView(View):

    def post(self, request, *args, **kwargs):
        json_data = json.loads(request.body)
        update = telebot.types.Update.de_json(json_data)
        tb.process_new_messages([update.message])
        return JsonResponse({"ok": "POST request processed"})


@tb.message_handler(content_types=['photo'])
def handle_photo(message):
    image = tb.get_file(message.photo[-1].file_id)
    # post = Post(image=image, description="photo_insta")
    # post.save()
    print("Photo received")

@tb.message_handler(commands=['help', 'start'])
def send_welcome(message):
    tb.reply_to(message,   
                ("Hi there, I am EchoBot.\n"
                "I am here to echo your kind words back to you."))

@tb.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    tb.reply_to(message, message.text)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>Sign up</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

posts/templates/posts/post_404.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1> No page found for {{ uri }}  </h1>
    <h3> {{ method }} response </h3>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="card" style="width: 30rem;">
    <img src = "{{ post.image.url }}" style="height: 40rem;">
    <div class="card-body">
        <h5 class="card-tittle">{{post.author.username}}</h5>
        <p class="card-text">{{ post.description }}</p>
        <p class="card-text">Likes : {{ post.likes.count }}</p>
        {% if user.is_authenticated %}
        <form action="{% url 'posts:like' pk=post.id %}" method="GET">
            {% if post.likes.count %}
                <button type="submit" class="btn btn-secondary">Dislike</button>
            {% else %}
                <button type="submit" class="btn btn-secondary">Like</button>
            {% endif %}
        </form>
    {% endif %}
    </div>
</div>
{% endblock %}

posts/templates/posts/post_edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit post {{post.id}}</h1>
<form action = "" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit post">
</form>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Create new post</h1>
<form action = "{% url 'new' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create post">
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% block content %}
    {% for post in object_list %}
    <div class="col-auto mb-3">
        <div class="card">
            <img src = "{{ post.image.url }}">
            <div class="card-body">
                <h5 class="card-tittle">{{post.author.username}}</h5>
                <p class="card-text">{{ post.description }}</p>
                <p class="card-text">Likes : {{ post.likes.count }}</p>
                <p class="id">Post_id: {{ post.id }}</p>
                <div class="btn-group-vertical">
                    <a href="{% url 'posts:detail' pk=post.id %}" method="GET">
                        <button type="submit" class="btn btn-secondary">Detail</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

posts/templates/posts/post_new.html
{% extends 'base.html' %}
{% block content %}
<h1>Create new post</h1>
<form action = "{% url 'posts:new' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create post">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <title>Things I eat</title>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a href="/">Thing I eat</a>
            <div class="navbar-brand" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item ml-4 mb-2">
                            <!-- {% csrf_token %}
                            <a href="{% url 'accounts:logout' %}">Logout</a> -->
                            <form class="logout-link" action= "{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-secondary">Logout</button>
                            </form>
                        </li>
                        <li class="nav-item ml-4 mb-2">
                            <form class="new-post" action="{% url 'posts:new' %}">
                                <button type="submit" class="btn btn-primary">New</button>
                            </form>
                        </li>
                        <li class="nav-item ml-4">
                            <p>{{user}}</p>
                        </li>
                    {% else %}
                        <li class="nav-item ml-4">
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item ml-4">
                            <a href="{% url 'accounts:signup' %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container mt-4">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>